// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TEMBMfVoxSDHiZMAxzK_h2VgobgIDGA',
    appId: '1:62237399971:web:a71ebdb2840b7aa8b95816',
    messagingSenderId: '62237399971',
    projectId: 'ei-flix',
    authDomain: 'ei-flix.firebaseapp.com',
    storageBucket: 'ei-flix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YbwLkgYyrVadgQLKN562KaBz-UiaVEc',
    appId: '1:62237399971:android:e9052ae7b175df6eb95816',
    messagingSenderId: '62237399971',
    projectId: 'ei-flix',
    storageBucket: 'ei-flix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsNghJfeRwhRlJyrJoh4yzqZCJmwBzOQ',
    appId: '1:62237399971:ios:07560b2aa7f79d65b95816',
    messagingSenderId: '62237399971',
    projectId: 'ei-flix',
    storageBucket: 'ei-flix.appspot.com',
    iosClientId: '62237399971-qe709sa98qdp8l08bcij94t4ghta226u.apps.googleusercontent.com',
    iosBundleId: 'com.example.elflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASsNghJfeRwhRlJyrJoh4yzqZCJmwBzOQ',
    appId: '1:62237399971:ios:07560b2aa7f79d65b95816',
    messagingSenderId: '62237399971',
    projectId: 'ei-flix',
    storageBucket: 'ei-flix.appspot.com',
    iosClientId: '62237399971-qe709sa98qdp8l08bcij94t4ghta226u.apps.googleusercontent.com',
    iosBundleId: 'com.example.elflix',
  );
}
